/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';

interface ChatMessageProps {
  text: string;
  time: string;
  isAi?: boolean;
}

const ChatMessage: React.FC<ChatMessageProps> = ({ text, time, isAi = false }) => {
  return (
    <MessageContainer isAi={isAi}>
      <MessageText isAi={isAi}>{text}</MessageText>
      <MessageTime>{time}</MessageTime>
    </MessageContainer>
  );
};

const MessageContainer = styled.div<{ isAi: boolean }>`
  display: flex;
  flex-direction: column;
  align-items: ${props => props.isAi ? 'flex-start' : 'flex-end'};
  margin-bottom: 16px;
`;

const MessageText = styled.p<{ isAi: boolean }>`
  background-color: ${props => props.isAi ? '#111922' : '#1b2735'};
  color: ${props => props.isAi ? '#b6bec3' : '#fff'};
  border-radius: ${props => props.isAi ? '0 12px 12px 12px' : '12px 0 12px 12px'};
  padding: 8px 12px;
  font-size: 12px;
  line-height: 18px;
  max-width: 80%;
`;

const MessageTime = styled.span`
  color: #b6bec3;
  font-size: 10px;
  line-height: 1.6;
  margin-top: 4px;
`;

export default ChatMessage;