/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';
import CheckCircleIcon from '@src/components/SVGIcons/CheckCircleIcon';

const dealData = [
  { label: 'Rehab assumption', value: '$15,000' },
  { label: 'Expected Sale Price', value: '$450,000' },
  { label: 'Projected Gross Margin', value: '$60,000' },
];

const DealSummary: React.FC = () => {
  return (
    <SummaryContainer>
      <SummaryTitle>Hurray! This is a great deal for:</SummaryTitle>
      <DealType>
        <CheckCircleIcon />
        <DealTypeText>Fix & Flip</DealTypeText>
      </DealType>
      {dealData.map((item, index) => (
        <DealItem key={index}>
          <DealItemLabel>{item.label}</DealItemLabel>
          <DealItemValue>{item.value}</DealItemValue>
        </DealItem>
      ))}
      <MessageTime>10:06 am</MessageTime>
    </SummaryContainer>
  );
};

const SummaryContainer = styled.div`
  background-color: #111922;
  border-radius: 12px;
  padding: 12px;
  margin-bottom: 16px;
`;

const SummaryTitle = styled.h2`
  color: #b6bec3;
  font-size: 12px;
  font-weight: 400;
  margin-bottom: 8px;
`;

const DealType = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
`;

const DealTypeText = styled.span`
  color: #fff;
  font-size: 12px;
  font-weight: 600;
`;

const DealItem = styled.div`
  background-color: #1b2735;
  border-radius: 4px;
  display: flex;
  justify-content: space-between;
  padding: 4px 12px;
  margin-top: 8px;
`;

const DealItemLabel = styled.span`
  color: #fff;
  font-size: 12px;
  font-weight: 600;
`;

const DealItemValue = styled.span`
  color: #30d158;
  font-size: 12px;
  font-weight: 600;
`;

const MessageTime = styled.span`
  color: #b6bec3;
  font-size: 10px;
  line-height: 1.6;
  display: block;
  text-align: right;
  margin-top: 4px;
`;

export default DealSummary;