/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Box, styled } from "@mui/material";

interface CarouselImageProps {
  src: string;
  alt: string;
}

const CarouselImage = styled("img")({
  aspectRatio: "1.57",
  objectFit: "contain",
  objectPosition: "center",
  cursor: "pointer",
  width: "88px",
  borderRadius: "8px",
  boxShadow:
    "0px 4px 12px 0px rgba(0, 0, 0, 0.15), 0px 16px 40px 0px rgba(0, 0, 0, 0.05)",
});

const CarouselContainer = styled(Box)({
  alignItems: "start",
  boxShadow:
    "0px 4px 12px 0px rgba(0, 0, 0, 0.15), 0px 16px 40px 0px rgba(0, 0, 0, 0.05)",
  overflowX: "auto",
  display: "flex",
  marginTop: "8px",
  width: "100%",
  gap: "var(--spacing-xs, 8px)",
  justifyContent: "start",
});

interface ImageCarouselProps {
  images: CarouselImageProps[];
  onImageClick: (src: string, alt: string) => void;
}

const ImageCarousel: React.FC<ImageCarouselProps> = ({
  images,
  onImageClick,
}) => {
  return (
    <CarouselContainer>
      {images.map((image, index) => (
        <CarouselImage
          key={index}
          src={image.src}
          alt={image.alt}
          onClick={() => onImageClick(image.src, image.alt)}
        />
      ))}
    </CarouselContainer>
  );
};

export default ImageCarousel;
