/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { Tabs, Tab, Box } from "@mui/material";
import { border, styled } from "@mui/system";
import InfoIcon from "@src/components/SVGIcons/InfoIcon";
import TabPanel from "./TabPanel";
import DealSummary from "./DealSummary";
import Comps from "./Comps";
import RehabScope from "./RehabScope";
import MarketStatistics from "./MarketStatistics";
import FlipCalculation from "./FlipCalculation";
import Assumption from "./Assumption";
import RentalAnalysis from "./RentalAnalysis";
import TitanCustomMode from "../TitanCustomMode/TitanCustomMode";

const StyledTabs = styled(Tabs)({
  borderRadius: "8px",
  display: "flex",
  alignItems: "center",
  justifyContent: "flex-start",
  flexWrap: "wrap",
  "& .MuiTabs-indicator": {
    display: "none", // Hides the indicator line
  },
});

const StyledTab = styled(Tab)(() => ({
  borderRadius: "999px",
  backgroundColor: "#1B2735",
  color: "#B6BEC3",
  fontWeight: 400,
  fontSize: "12px",
  fontFamily: "Poppins, sans-serif",
  minHeight: "30px",
  height: "30px",
  marginRight: "12px",
  border: `1px solid #B6BEC3`,
  disableRipple: true,
  disableFocusRipple: true,
  "&.Mui-selected": {
    backgroundColor: "rgba(64, 200, 224, 1)",
    color: "#fff",
    fontWeight: 600,
  },
}));

const TitanModeWrapper = styled(Box)({
  display: "flex",
  alignItems: "center",
  gap: "8px",
});

const DealAnalysisTabs = () => {
  const [value, setValue] = useState(0);

  const handleChange = (event: React.SyntheticEvent, newValue: number) => {
    setValue(newValue);
  };

  const tabData = [
    { label: "Deal Summary", component: <DealSummary /> },
    { label: "Comps", component: <Comps /> },
    { label: "Rehab Scope", component: <RehabScope /> },
    { label: "Market Statistics", component: <MarketStatistics /> },
    { label: "Flip Calculation", component: <FlipCalculation /> },
    { label: "Assumption", component: <Assumption /> },
    { label: "Rental Analysis", component: <RentalAnalysis /> },
  ];

  return (
    <Box
      sx={{
        display: "flex",
        alignItems: "center",
        justifyContent: "space-between",
      }}
    >
      <StyledTabs
        value={value}
        onChange={handleChange}
        aria-label="Deal analysis tabs"
      >
        {tabData.map((tab, index) => (
          <StyledTab
            key={index}
            label={tab.label}
            id={`tab-${index}`}
            aria-controls={`tabpanel-${index}`}
          />
        ))}
      </StyledTabs>
      {tabData.map((tab, index) => (
        <TabPanel key={index} value={value} index={index}>
          {tab.component}
        </TabPanel>
      ))}
      <TitanModeWrapper>
        <TitanCustomMode />
      </TitanModeWrapper>
    </Box>
  );
};

export default DealAnalysisTabs;
