/**
 * This code was generated by Builder.io.
 */
import React from "react";
import {
  TextField,
  Button,
  Typography,
  Box,
  InputAdornment,
} from "@mui/material";
import BackArrowIcon from "@src/components/SVGIcons/BackArrowIcon";

interface PropertyOfferProps {
  address: string;
  offerPrice: number;
}

const PropertyOffer: React.FC<PropertyOfferProps> = ({
  address,
  offerPrice,
}) => {
  return (
    <Box
      sx={{
        display: "flex",
        alignItems: "center",
        gap: "20px",
        justifyContent: "space-between",
        height: "90px",
      }}
    >
      <Box sx={{ display: "flex", alignItems: "center", gap: "20px" }}>
        <Box sx={{ display: "flex", alignItems: "center", gap: "20px" }}>
          <BackArrowIcon />
          <Typography variant="h6" color="#f7f7f7">
            {address}
          </Typography>
        </Box>
        <Button sx={{ border: "1px dotted" }}>GREAT DEAL</Button>
      </Box>
      <Box
        sx={{
          display: "flex",
          alignItems: "center",
          gap: "20px",
        }}
      >
        <Typography variant="subtitle2" color="#f7f7f7">
          {" "}
          Offer Price
        </Typography>
        <Box
          sx={{
            display: "flex",
            alignItems: "center",
            gap: "20px",
            height: "40px",
          }}
        >
          <TextField
            fullWidth
            value="375,000"
            slotProps={{
              input: {
                endAdornment: (
                  <InputAdornment position="start">
                    <Typography variant="body1" color="#f7f7f7">
                      USD
                    </Typography>
                  </InputAdornment>
                ),
                sx: {
                  height: "40px",
                  padding: 0,
                  boxSizing: "border-box",
                  color: "#f7f7f7",
                  border: "#f7f7f7 1px solid",
                },
              },
            }}
          />

          <Button variant="contained" color="primary" fullWidth>
            Make an Offer
          </Button>
        </Box>
      </Box>
    </Box>
  );
};

export default PropertyOffer;
