/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';
import { Typography, Box } from '@material-ui/core';

interface EstimatedProfitProps {
  amount: string;
}

export const EstimatedProfit: React.FC<EstimatedProfitProps> = ({ amount }) => (
  <ProfitWrapper>
    <Typography variant="body2" className="profit-label">
      Estimated Profit (FLIP)
    </Typography>
    <Typography variant="h6" className="profit-amount">
      {amount}
    </Typography>
  </ProfitWrapper>
);

const ProfitWrapper = styled(Box)`
  display: flex;
  justify-content: space-between;
  align-items: center;
  background-color: rgba(17, 25, 34, 1);
  border-radius: 4px;
  padding: 8px 12px;

  .profit-label {
    color: #fff;
    font-weight: 600;
  }

  .profit-amount {
    color: #30d158;
    font-weight: 500;
    letter-spacing: -0.18px;
  }
`;

export default EstimatedProfit;