/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';
import { Typography, Box } from '@material-ui/core';

interface FinancialDataItemProps {
  label: string;
  value: string;
}

export const FinancialDataItem: React.FC<FinancialDataItemProps> = ({ label, value }) => (
  <ItemWrapper>
    <Typography variant="body2" className="item-label">
      {label}
    </Typography>
    <Typography variant="body2" className="item-value">
      {value}
    </Typography>
  </ItemWrapper>
);

const ItemWrapper = styled(Box)`
  display: flex;
  justify-content: space-between;
  align-items: center;
  padding: 4px 0;

  .item-label {
    color: #b6bec3;
    font-weight: 400;
  }

  .item-value {
    color: #fff;
    font-weight: 600;
    text-align: right;
  }
`;

export default FinancialDataItem;