/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Box, Typography, Paper } from "@mui/material";
import { styled } from "@mui/system";
import ArrowUpIcon from "@src/components/SVGIcons/ArrowUpIcon";

interface InternalRateReturnProps {
  value: number;
  percentage: number;
}

const StyledPaper = styled(Paper)(({ theme }) => ({
  borderRadius: theme.shape.borderRadius,
  background:
    "linear-gradient(96deg, rgba(35, 51, 71, 0.8) 0%, rgba(30, 44, 60, 0.9) 100%)",
  backdropFilter: "blur(12px)",
  maxWidth: 299,
  padding: theme.spacing(1, 2, 0.5, 2),
  display: "flex",
  flexDirection: "column",
  gap: theme.spacing(0.5),
}));

const Title = styled(Typography)(({ theme }) => ({
  fontSize: 12,
  color: theme.palette.text.secondary,
  fontWeight: 400,
}));

const Content = styled(Box)(({ theme }) => ({
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(1),
  marginTop: theme.spacing(0.5),
}));

const Value = styled(Typography)(({ theme }) => ({
  color: theme.palette.common.white,
  fontSize: 32,
  fontWeight: 300,
  lineHeight: 1,
  letterSpacing: -0.64,
}));

const Indicator = styled(Box)(({ theme }) => ({
  borderRadius: 40,
  backgroundColor: theme.palette.success.main,
  display: "flex",
  alignItems: "center",
  gap: theme.spacing(0.5),
  padding: theme.spacing(0.5, 1),
  fontSize: 12,
  color: theme.palette.common.white,
  fontWeight: 600,
}));

const InternalRateReturn: React.FC<InternalRateReturnProps> = ({
  value,
  percentage,
}) => {
  return (
    <StyledPaper elevation={0}>
      <Title variant="body2">Internal Rate Return (IRR)</Title>
      <Content>
        <Value variant="h4">
          <Box component="span" fontSize={24}>
            $
          </Box>
          {value.toLocaleString()}
        </Value>
        <Indicator>
          <ArrowUpIcon />
          <Typography variant="body2">{percentage.toFixed(1)}%</Typography>
        </Indicator>
      </Content>
    </StyledPaper>
  );
};

export default InternalRateReturn;
