/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@mui/material/styles';
import { Typography } from '@mui/material';

interface AssumptionRowProps {
  description: string;
  shortTerm: string;
  longTerm: string;
}

const AssumptionRow: React.FC<AssumptionRowProps> = ({ description, shortTerm, longTerm }) => {
  return (
    <StyledRow>
      <Typography variant="body2" className="description">{description}</Typography>
      <Typography variant="body2" className="value">{shortTerm}</Typography>
      <Typography variant="body2" className="value">{longTerm}</Typography>
    </StyledRow>
  );
};

const StyledRow = styled('div')(({ theme }) => ({
  display: 'flex',
  alignItems: 'center',
  gap: theme.spacing(1.5),
  marginTop: theme.spacing(0.5),
  marginBottom: theme.spacing(0.5),
  '& .description': {
    flex: '0 0 180px',
    fontWeight: 400,
  },
  '& .value': {
    flex: 1,
    textAlign: 'right',
  },
}));

export default AssumptionRow;