/**
 * This code was generated by Builder.io.
 */
export interface FinancingAssumption {
  id: string;
  description: string;
  shortTerm: string;
  longTerm: string;
}

export const financingAssumptionData: FinancingAssumption[] = [
  { id: 'minDscr', description: 'Min. DSCR', shortTerm: '1.1x', longTerm: '1.25x' },
  { id: 'maxLtvAr', description: 'Max. LTV (AR)', shortTerm: '75%', longTerm: '75%' },
  { id: 'maxLtc', description: 'Max. LTC', shortTerm: '85%', longTerm: 'NA' },
  { id: 'minDownPayment', description: 'Min. Down Payment %', shortTerm: '30%', longTerm: '30%' },
  { id: 'loanAmount', description: 'Loan Amount', shortTerm: 'Calculated', longTerm: 'Calculated' },
  { id: 'closingCosts', description: 'Closing Costs', shortTerm: '3.50%', longTerm: '4.00%' },
  { id: 'loanFees', description: 'Loan Fees', shortTerm: '1.00%', longTerm: '1.00%' },
  { id: 'term', description: 'Term (in months)', shortTerm: '12', longTerm: '60' },
  { id: 'interestOnlyPeriod', description: 'Interest Only Period', shortTerm: 'Yes', longTerm: 'No' },
  { id: 'interestOnlyPeriodLength', description: 'Interest Only Period Length', shortTerm: '12', longTerm: 'NA' },
  { id: 'amortizing', description: 'Amortizing?', shortTerm: 'No', longTerm: 'Yes' },
  { id: 'amortizingPeriod', description: 'Amortizing Period (in months)', shortTerm: 'NA', longTerm: '360' },
  { id: 'interestRate', description: 'Interest Rate', shortTerm: '12%', longTerm: '7%' },
  { id: 'rentalGrowth', description: 'Rental Growth', shortTerm: 'No', longTerm: '15%' },
];