/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Switch, FormControlLabel } from "@mui/material";
import { useFormContext, Controller } from "react-hook-form";
import PercentageIcon from "../SVGIcons/PercentageIcon";

interface TitanCustomModeSwitchProps {
  name: string;
  label: string;
}

const TitanCustomModeSwitch: React.FC<TitanCustomModeSwitchProps> = ({
  name,
  label,
}) => {
  const { control } = useFormContext();

  return (
    <Controller
      name={name}
      control={control}
      render={({ field }) => (
        <FormControlLabel
          control={
            <Switch
              {...field}
              checked={field.value}
              onChange={(e) => field.onChange(e.target.checked)}
              icon={<PercentageIcon />}
              checkedIcon={<PercentageIcon />}
            />
          }
          label={label}
        />
      )}
    />
  );
};

export default TitanCustomModeSwitch;
