/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { useForm, FormProvider } from "react-hook-form";
import TitanCustomModeSwitch from "./TitanCustomModeSwitch";
import TitanCustomModeLabel from "./TitanCustomModeLabel";

const TitanCustomMode: React.FC = () => {
  const methods = useForm({
    defaultValues: {
      titanCustomMode: false,
    },
  });

  return (
    <FormProvider {...methods}>
      <form>
        <section className="titan-custom-mode-container">
          <TitanCustomModeLabel text="Titan Custom Mode" />
          <TitanCustomModeSwitch name="titanCustomMode" label="" />
        </section>
      </form>
      <style>{`
        .titan-custom-mode-container {
          display: flex;
          align-items: center;
          justify-content: space-between;
        }
      `}</style>
    </FormProvider>
  );
};

export default TitanCustomMode;
