/**
 * This code was generated by Builder.io.
 */
import React from "react";
import InfoCard from "@src/components/InfoCard/InfoCard";

const InfoCardContainer: React.FC = () => {
  const carouselImages = [
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/b4de3e107a8e9ad64be1985f274327b6b9ed01a19bb51b069cf59f3c99e3f4cc?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 1",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/20681d053fed863bb33199ea75bbb567b063c9dd95824f503d94bc015ddff6b3?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 2",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/582494efc3c3dceeb6961f6b460ac72746c71379128e23bf99b08586c97a6154?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 3",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/88b4ffcec28bc0656cb6c04e9d812dec6638fc9f9c8e973caace645fa375c1e0?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 4",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/a7c054906c1b384cc8f0e85895b23c961d1e7aa2ceb75acab0d2ef87cbcd7253?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 5",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 6",
    },
    {
      src: "https://cdn.builder.io/api/v1/image/assets/bcfb80a41ce34cb3b0015d52247ca7ff/ca046a62429c37a5d23bb1958ac42ad182f0ee37fd489e5948612e413e1fc012?apiKey=bcfb80a41ce34cb3b0015d52247ca7ff&",
      alt: "Carousel image 7",
    },
  ];

  return (
    <InfoCard
      mainImageSrc="https://letsenhance.io/static/8f5e523ee6b2479e26ecc91b9c25261e/1015f/MainAfter.jpg"
      mainImageAlt="Main info card image"
      carouselImages={carouselImages}
    />
  );
};

export default InfoCardContainer;
