/**
 * This code was generated by Builder.io.
 */
import React, { useState } from "react";
import { Box, styled } from "@mui/material";
import ImageCarousel from "@src/components/ImageCarousel/ImageCarousel";
import ImageWithControls from "../ImageWithControls/ImageWithControls";

const InfoCardContainer = styled(Box)({
  alignSelf: "stretch",
  backdropFilter: "blur(4px)",
  display: "flex",
  maxWidth: "390px",
  flexDirection: "column",
  overflow: "hidden",
  justifyContent: "start",
  gap: "var(--spacing-xs, 8px)",
});

interface InfoCardProps {
  mainImageSrc: string;
  mainImageAlt: string;
  carouselImages: Array<{ src: string; alt: string }>;
}

const InfoCard: React.FC<InfoCardProps> = ({
  mainImageSrc,
  mainImageAlt,
  carouselImages,
}) => {
  const [mainImage, setMainImage] = useState({
    src: mainImageSrc,
    alt: mainImageAlt,
  });

  const handleImageClick = (src: string, alt: string) => {
    setMainImage({ src, alt });
  };

  return (
    <InfoCardContainer>
      <ImageWithControls imageSrc={mainImage.src} />

      <ImageCarousel images={carouselImages} onImageClick={handleImageClick} />
    </InfoCardContainer>
  );
};

export default InfoCard;
