/**
 * This code was generated by Builder.io.
 */
import React from "react";
import PropertyOffer from "../PropertyOffer/PropertyOffer";

const PropertyOfferPage: React.FC = () => {
  return (
    <PropertyOffer
      address="2821 Lake Sevilla, Palm Harbor, TX"
      offerPrice={375000}
    />
  );
};

export default PropertyOfferPage;
