/**
 * This code was generated by Builder.io.
 */
import React from "react";
import {
  Box,
  Typography,
  Button as MuiButton,
  Checkbox,
  FormControlLabel,
} from "@mui/material";
import { styled } from "@mui/system";
import InputField from "./InputField";

interface LoginFormProps {
  onLogin: () => void;
  onForgotPassword: () => void;
  onSignUp: () => void;
}

const LoginContainer = styled(Box)(({ theme }) => ({
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
  justifyContent: "start",
  padding: "0 24px",
  [theme.breakpoints.down("md")]: {
    padding: "0 20px",
  },
}));

const LoginForm = styled(Box)(({ theme }) => ({
  transform: "rotate(-0.32deg)",
  borderRadius: "16px",
  background:
    "linear-gradient(96deg, rgba(35, 51, 71, 0.8) 0%, rgba(30, 44, 60, 0.9) 100%)",
  display: "flex",
  minHeight: "432px",
  width: "532px",
  maxWidth: "100%",
  padding: "32px 24px",
  flexDirection: "column",
  justifyContent: "start",
  gap: "32px",
  [theme.breakpoints.down("md")]: {
    padding: "32px 20px",
  },
}));

const LoginTitle = styled(Typography)(({ theme }) => ({
  alignSelf: "start",
  color: "#111922",
  textAlign: "center",
  letterSpacing: "-0.24px",
  fontFamily: "Comfortaa, sans-serif",
  fontWeight: 700,
  fontSize: "24px",
  [theme.breakpoints.down("md")]: {
    maxWidth: "100%",
  },
}));

const LoginFields = styled(Box)({
  display: "flex",
  width: "100%",
  flexDirection: "column",
  fontFamily: "Poppins, sans-serif",
  justifyContent: "start",
});

const ForgotPassword = styled(MuiButton)({
  color: "#5c86d7",
  fontSize: "14px",
  fontWeight: 400,
  lineHeight: 2,
  alignSelf: "flex-end",
  marginTop: "16px",
  textTransform: "none",
});

const RememberMe = styled(Box)({
  alignSelf: "start",
  display: "flex",
  marginTop: "32px",
  minHeight: "25px",
  alignItems: "center",
  gap: "12px",
  justifyContent: "start",
});

const LoginFooter = styled(Box)({
  display: "flex",
  marginTop: "24px",
  alignItems: "start",
  gap: "4px",
  justifyContent: "start",
  font: "400 14px/2 Poppins, sans-serif",
});

const SignUpLink = styled(MuiButton)({
  color: "#5c86d7",
  background: "none",
  border: "none",
  cursor: "pointer",
  font: "inherit",
  padding: 0,
  textTransform: "none",
});

const LoginButton = styled(MuiButton)(({ theme }) => ({
  alignSelf: "stretch",
  borderRadius: "8px",
  backgroundColor: "#5c86d7",
  minHeight: "49px",
  width: "100%",
  color: "#fff",
  textAlign: "center",
  padding: "12px 32px",
  font: "400 16px Poppins, sans-serif",
  textTransform: "none",
  "&:hover": {
    backgroundColor: "#4a6cb0",
  },
  [theme.breakpoints.down("md")]: {
    maxWidth: "100%",
    whiteSpace: "initial",
    padding: "12px 20px",
  },
}));

const LoginFormComponent: React.FC<LoginFormProps> = ({
  onLogin,
  onForgotPassword,
  onSignUp,
}) => {
  return (
    <LoginContainer>
      <LoginForm>
        <LoginTitle variant="h1">Login</LoginTitle>
        <LoginFields component="form">
          <InputField label="Username" value="david007" type="text" />
          <InputField label="Password" value="••••••••" type="password" />
          <ForgotPassword onClick={onForgotPassword}>
            Forgot password
          </ForgotPassword>
        </LoginFields>
        <LoginButton onClick={onLogin} variant="contained">
          Login
        </LoginButton>
        <RememberMe>
          <FormControlLabel
            control={<Checkbox />}
            label="Remember me"
            sx={{
              "& .MuiTypography-root": {
                fontFamily: "Poppins, sans-serif",
                fontSize: "14px",
              },
            }}
          />
        </RememberMe>
      </LoginForm>
      <LoginFooter>
        <Typography component="p" sx={{ color: "#111922" }}>
          Don't have an account?
        </Typography>
        <SignUpLink onClick={onSignUp}>Sign up now</SignUpLink>
      </LoginFooter>
    </LoginContainer>
  );
};

export default LoginFormComponent;
