/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Typography, Link, Box } from "@mui/material";

interface FooterProps {
  // Add any props if needed
}

const Footer: React.FC<FooterProps> = () => {
  return (
    <Box sx={{ textAlign: "center", marginTop: "20px" }}>
      <Typography variant="body2" gutterBottom>
        Don't have an account? <Link href="/signup">Sign up</Link>
      </Typography>
      <Typography variant="body2">
        <Link href="/forgot-password">Forgot password?</Link>
      </Typography>
    </Box>
  );
};

export default Footer;
