/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Typography, Box } from "@mui/material";

interface HeaderProps {
  // Add any props if needed
}

const Header: React.FC<HeaderProps> = () => {
  return (
    <Box sx={{ textAlign: "center", marginBottom: "20px" }}>
      <Typography variant="h4" component="h1" gutterBottom>
        Welcome Back
      </Typography>
      <Typography variant="subtitle1">Please log in to continue</Typography>
    </Box>
  );
};

export default Header;
