/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { TextField, Button, Box } from "@mui/material";

interface LoginFormProps {
  // Add any props if needed
}

const LoginForm: React.FC<LoginFormProps> = () => {
  return (
    <Box
      component="form"
      sx={{
        display: "flex",
        flexDirection: "column",
        gap: "20px",
        maxWidth: "300px",
        margin: "0 auto",
      }}
    >
      <TextField
        id="email"
        label="Email"
        variant="outlined"
        type="email"
        fullWidth
        required
      />
      <TextField
        id="password"
        label="Password"
        variant="outlined"
        type="password"
        fullWidth
        required
      />
      <Button variant="contained" type="submit" fullWidth>
        Log In
      </Button>
    </Box>
  );
};

export default LoginForm;
