/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Container, Box } from "@mui/material";
import LoginForm from "./LoginForm";
import Header from "./Header";
import Footer from "./Footer";

interface LoginPageProps {
  // Add any props if needed
}

const LoginPage: React.FC<LoginPageProps> = () => {
  return (
    <Container maxWidth="sm">
      <Box
        sx={{
          borderRadius: "24px",
          backgroundColor: "rgba(249, 249, 249, 1)",
          display: "flex",
          flexDirection: "column",
          minHeight: "908px",
          border: "4px solid rgba(228, 234, 244, 0.2)",
          padding: "20px",
        }}
      >
        <Header />
        <LoginForm />
        <Footer />
      </Box>
    </Container>
  );
};

export default LoginPage;
