/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';

interface AnalysisDataRowProps {
  label: string;
  value: string;
}

export const AnalysisDataRow: React.FC<AnalysisDataRowProps> = ({ label, value }) => {
  return (
    <RowContainer>
      <Label>{label}</Label>
      <Value>{value}</Value>
    </RowContainer>
  );
};

const RowContainer = styled.div`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 12px;
  font-size: 12px;
  color: var(--BodySecondary, #b6bec3);
`;

const Label = styled.div`
  font-weight: 400;
  align-self: stretch;
  width: 180px;
  margin: auto 0;
`;

const Value = styled.div`
  text-align: right;
  font-weight: 600;
  align-self: stretch;
  flex: 1;
  margin: auto 0;
`;