/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import styled from 'styled-components';

interface AnalysisHeaderProps {
  title: string;
  subtitle: string;
}

export const AnalysisHeader: React.FC<AnalysisHeaderProps> = ({ title, subtitle }) => {
  return (
    <HeaderContainer>
      <Title>{title}</Title>
      <Subtitle>{subtitle}</Subtitle>
    </HeaderContainer>
  );
};

const HeaderContainer = styled.header`
  display: flex;
  width: 100%;
  align-items: center;
  gap: 12px;
  font-size: 14px;
  color: var(--Headings, #fff);
  font-weight: 600;
  line-height: 2;
`;

const Title = styled.h1`
  align-self: stretch;
  width: 180px;
  margin: auto 0;
`;

const Subtitle = styled.h2`
  text-align: right;
  align-self: stretch;
  flex: 1;
  margin: auto 0;
`;