/**
 * This code was generated by Builder.io.
 */
import BuildingInfoRow from "@src/components/BuildingInfoRow/BuildingInfoRow";
import InfoCardContainer from "@src/components/InfoCard/InfoCardContainer";
import PropertyDetailsMainPage from "@src/components/PropertyDetails/PropertyDetailsMainPage";
import TrendAnalysis from "@src/components/TrendAnalysis/TrendAnalysis";
import React from "react";
import styled from "styled-components";

export const AnalysisColumn: React.FC = () => {
  return (
    <StyledAnalysisColumn>
      <TrendAnalysis />
      <DetailsRow>
        <PropertyDetailsMainPage />
        <InfoCardContainer />
      </DetailsRow>
      <BuildingInfoRow />
    </StyledAnalysisColumn>
  );
};

const StyledAnalysisColumn = styled.div`
  align-self: flex-start;
  display: flex;
  min-width: 240px;
  flex-direction: column;
  justify-content: flex-start;
  flex: 1;
  flex-basis: 0%;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;

const DetailsRow = styled.div`
  display: flex;
  margin-top: 24px;
  width: 100%;
  gap: 12px;
  justify-content: flex-start;

  @media (max-width: 991px) {
    max-width: 100%;
  }
`;
