/**
 * This code was generated by Builder.io.
 */
import styled from "styled-components";

import { AnalysisColumn } from "./AnalysisColumn";
import Header from "@src/components/Header/Header";
import PropertyOfferPage from "@src/components/pages/PropertyOfferPage";
import DealAnalysisTabs from "@src/components/DealAnalysisTabs/DealAnalysisTabs";
import AiChatComponent from "@src/components/AiChatModule/AiChatComponent";
import { Box } from "@mui/material";

const DealAnalysisDetails = () => {
  return (
    <StyledDealAnalysisDetails>
      <Header />
      <Box sx={{ p: "12px" }}>
        <PropertyOfferPage />
        <DealAnalysisTabs />
        <MainContent>
          <WidgetContainer>
            <AnalysisColumn />
            <AiChatComponent />
          </WidgetContainer>
        </MainContent>
      </Box>
    </StyledDealAnalysisDetails>
  );
};

const StyledDealAnalysisDetails = styled.main`
  border-radius: 24px;
  display: flex;
  flex-direction: column;
  overflow: hidden;
`;

const MainContent = styled("Box")({
  display: "flex",
  minHeight: "824px",
  width: "100%",
  flexDirection: "column",
  justifyContent: "center", // centers content vertically
  alignItems: "center", // centers content horizontally

  "@media (max-width: 991px)": {
    maxWidth: "100%",
    padding: "0 20px",
  },
});

const WidgetContainer = styled("Box")({
  display: "flex",
  marginTop: "32px",
  maxWidth: "100%",
  width: "1552px",
  gap: "24px",
  justifyContent: "center",
  flex: "1",
  flexWrap: "wrap",
  height: "100%",
});

export default DealAnalysisDetails;
