/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { styled } from "@mui/material/styles";
import {
  Table,
  TableBody,
  TableCell,
  TableContainer,
  TableHead,
  TableRow,
  Paper,
} from "@mui/material";
import { useForm, Controller } from "react-hook-form";
import { TextField } from "@mui/material";

interface YearData {
  year: string;
  monthlyRent: number;
  grossRentalIncome: number;
  otherIncome: number;
  totalGrossIncome: number;
  vacancyLoss: number;
  netIncome: number;
  propertyManagementFees: number;
  repairsAndMaintenance: number;
  utilities: number;
  insurance: number;
  propertyTaxes: number;
  capitalReserves: number;
  totalOperatingExpenses: number;
  netOperatingIncome: number;
  debtService: number;
  cashFlow: number;
}

interface FiveYearPLTableProps {
  initialData: YearData[];
}

const StyledTableContainer = styled(TableContainer)(({ theme }) => ({
  borderRadius: theme.spacing(1),
  background:
    "linear-gradient(96deg, rgba(35, 51, 71, 0.8) 0%, rgba(30, 44, 60, 0.9) 100%)",
  backdropFilter: "blur(4px)",
  padding: theme.spacing(1.5),
  fontFamily: "Poppins, sans-serif",
  fontWeight: 600,
}));

const StyledTableCell = styled(TableCell)(({ theme }) => ({
  color: theme.palette.common.white,
  borderBottom: "1px solid rgba(80, 94, 110, 1)",
  padding: theme.spacing(1),
  "&.header": {
    fontSize: 14,
    lineHeight: 2,
  },
  "&.data": {
    fontSize: 12,
    color: "#b6bec3",
  },
  "&.total": {
    color: theme.palette.common.white,
  },
}));

const FiveYearPLTable: React.FC<FiveYearPLTableProps> = ({ initialData }) => {
  const { control } = useForm<YearData[]>({
    defaultValues: initialData,
  });

  return (
    <StyledTableContainer component={Paper}>
      <Table aria-label="5 Year P&L Table">
        <TableHead>
          <TableRow>
            <StyledTableCell className="header">5 Year P&L</StyledTableCell>
            <StyledTableCell className="header">Assumption</StyledTableCell>
            {initialData.map((year, index) => (
              <StyledTableCell key={index} align="right" className="header">
                {year.year}
              </StyledTableCell>
            ))}
          </TableRow>
        </TableHead>
        <TableBody>
          {Object.keys(initialData[0])
            .slice(1)
            .map((key) => (
              <TableRow key={key}>
                <StyledTableCell className="data">
                  {key.replace(/([A-Z])/g, " $1").trim()}
                </StyledTableCell>
                <StyledTableCell className="data">
                  {key === "vacancyLoss"
                    ? "8%"
                    : key === "propertyManagementFees"
                    ? "10%"
                    : key === "repairsAndMaintenance"
                    ? "7.50%"
                    : key === "insurance"
                    ? "2% of Purchase Price"
                    : key === "propertyTaxes"
                    ? "1.25% of Assessed Value"
                    : key === "capitalReserves"
                    ? "0.5% Building Cost"
                    : "Toggle"}
                </StyledTableCell>
                {initialData.map((year, yearIndex) => (
                  <StyledTableCell
                    key={yearIndex}
                    align="right"
                    className={
                      key === "netIncome" ||
                      key === "netOperatingIncome" ||
                      key === "cashFlow"
                        ? "total"
                        : "data"
                    }
                  >
                    <Controller
                      name={`${yearIndex}.${key}`}
                      control={control}
                      render={({ field }) => (
                        <TextField
                          {...field}
                          variant="standard"
                          InputProps={{
                            disableUnderline: true,
                            style: { color: "inherit", textAlign: "right" },
                          }}
                        />
                      )}
                    />
                  </StyledTableCell>
                ))}
              </TableRow>
            ))}
        </TableBody>
      </Table>
    </StyledTableContainer>
  );
};

export default FiveYearPLTable;
