/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { styled } from '@mui/material/styles';
import { Grid, Typography } from '@mui/material';
import { MetricData } from '@src/types/metrics';

const MetricRow: React.FC<MetricData> = ({ label, assumption, values }) => {
  return (
    <Grid container spacing={2} alignItems="center">
      <Grid item xs={3}>
        <Typography variant="body2">{label}</Typography>
      </Grid>
      <Grid item xs={1.8}>
        <StyledTypography align="right">{assumption}</StyledTypography>
      </Grid>
      {values.map((value, index) => (
        <Grid item xs={1.8} key={index}>
          <StyledTypography align="right">{value}</StyledTypography>
        </Grid>
      ))}
    </Grid>
  );
};

const StyledTypography = styled(Typography)(({ theme }) => ({
  fontWeight: 600,
}));

export default MetricRow;