/**
 * This code was generated by Builder.io.
 */
import React from "react";
import { Typography, Box, Divider } from "@mui/material";
import { useForm } from "react-hook-form";
import InfoRow from "@src/components/BuildingInfo/InfoRow";

interface BuildingInfoProps {
  yearBuilt: string;
  levels: string;
  garage: string;
  foundation: string;
  construction: string;
  roofConstruction: string;
  basement: string;
  className: string;
}

const BuildingInfo: React.FC<BuildingInfoProps> = ({
  yearBuilt,
  levels,
  garage,
  foundation,
  construction,
  roofConstruction,
  basement,
  className,
}) => {
  const { control } = useForm<BuildingInfoProps>();

  const infoData = [
    { label: "Year Built", value: yearBuilt },
    { label: "Levels", value: levels },
    { label: "Garage/Carport", value: garage },
    { label: "Foundation", value: foundation },
    { label: "Construction", value: construction },
    { label: "Roof Construction", value: roofConstruction },
    { label: "Basement", value: basement },
  ];

  return (
    <Box className={`building-info ${className}`}>
      <Typography variant="h6" className="building-title">
        Building
      </Typography>
      <Divider className="info-divider" />
      <Box className="info-container">
        {infoData.map((item, index) => (
          <React.Fragment key={index}>
            <InfoRow label={item.label} value={item.value} control={control} />
            {index < infoData.length - 1 && (
              <Divider className="info-divider" />
            )}
          </React.Fragment>
        ))}
      </Box>
      <style>{`
        .building-info {
          border-radius: 8px;
          background: linear-gradient(
            96deg,
            rgba(35, 51, 71, 0.8) 0%,
            rgba(30, 44, 60, 0.9) 100%
          );
          backdrop-filter: blur(4px);
          padding: 12px;
          font-family: Poppins, sans-serif;
    
      
        }
        .building-title {
          color: #fff;
          font-size: 14px;
          font-weight: 600;
          line-height: 2;
        }
        .info-divider {
          border-color: rgba(80, 94, 110, 1);
          margin: 16px 0 4px;
        }
        .info-container {
          padding: 0 4px;
          font-size: 12px;
        }
      `}</style>
    </Box>
  );
};

export default BuildingInfo;
