/**
 * This code was generated by Builder.io.
 */
import React from 'react';
import { Typography, Box } from '@mui/material';
import { Control, Controller } from 'react-hook-form';

interface InfoRowProps {
  label: string;
  value: string;
  control: Control<any>;
}

const InfoRow: React.FC<InfoRowProps> = ({ label, value, control }) => {
  return (
    <Box className="info-row">
      <Controller
        name={label.toLowerCase().replace(/\s/g, '')}
        control={control}
        defaultValue={value}
        render={({ field }) => (
          <>
            <Typography className="info-label">{label}</Typography>
            <Typography className="info-value">{field.value}</Typography>
          </>
        )}
      />
      <style jsx>{`
        .info-row {
          display: flex;
          align-items: center;
          justify-content: space-between;
          gap: 12px;
          margin: 4px 0;
        }
        .info-label {
          color: #b6bec3;
          font-weight: 400;
        }
        .info-value {
          color: #fff;
          text-align: right;
          font-weight: 600;
        }
      `}</style>
    </Box>
  );
};

export default InfoRow;