/**
 * This code was generated by Builder.io.
 */
import React from "react";
import styled from "styled-components";
import Controls from "@src/components/Controls/Controls";

interface ImageWithControlsProps {
  imageSrc: string;
}

const ImageWithControls: React.FC<ImageWithControlsProps> = ({ imageSrc }) => {
  return (
    <ImageContainer>
      <ImageWrapper>
        <BackgroundImage loading="lazy" src={imageSrc} alt="" />
        <Controls />
      </ImageWrapper>
    </ImageContainer>
  );
};

const ImageContainer = styled.section`
  border-radius: 0;
  display: flex;
  max-width: 404px;
  flex-direction: column;
`;

const ImageWrapper = styled.div`
  display: flex;
  flex-direction: column;
  border-radius: 8px;
  position: relative;
  aspect-ratio: 2.104;
  width: 100%;
  align-items: flex-end;
  padding: 10px 22px 84px;
  @media (max-width: 640px) {
    min-height: 400px;
  }
`;

const BackgroundImage = styled.img`
  position: absolute;
  inset: 0;
  height: 100%;
  width: 100%;
  object-fit: cover;
  object-position: center;
`;

const StyledControls = styled(Controls)`
  position: relative;
  display: flex;
  flex-direction: column;
  margin-top: 20px;
`;

export default ImageWithControls;
